* expectations from ethical hacker
** privary
** intellectual property
** disclosure
** areas of expertise
** no unauthorized usage
** no illegal activities
** authorization
** dont be bad guy
* skills required
** expert with programs and networks
*** tcp/ip
** proficient with vulnerability research
** learn different hacking techniques
** follow a strict code of conduct
* types of pen test
** black box
** gray box
** white box
* fundamentals of information security
** authenticity
** integrity
** availability
** confidentiality
** non-repudiation
* motivations for attackers
** disrupt business continuity
** steal data
** create fear and chaos
** financial losses
** publicize political or relegious beliefs
** achieve states military objectives
** reputation of target
** revenge
** ransom
* types of attacks
** passive
** active attacks
** close-in attacks
** insider attacks
** distribution attacks
* terminology
** exploit
*** a way of circumventing security
** hack values
*** value hacker associates with the system
** vulnerability
*** weakness in the implementation of a system
** target of evaluation
** zero-day attack
*** attack where no patch or fix available
*** ms knows that there is vulnerability but fix is still not available
** daisy chaining
*** using one node in environment to attack other nodes in environment
* security threat
** hosts, natural, physical, applications, human, network
** host
*** footprinting
**** we can find out the system by seeing response and decide attacks to launch
*** physical security
*** passwords
*** malware
*** denial of service
*** unauthorized access
*** privilege escalation
*** back doors
** natural
*** earthquakes
*** hurricanes
*** floods
*** natural disasters
** physial
*** theft
*** impact
*** power
*** end of life
** applications
*** configuration
*** buffer overflow
*** lazy coding
*** data / input validation
** human
*** malicious employees
*** lack of training
*** social networking
*** hackers
** network
*** sniffing / eavesdropping
*** ARP poisoning
**** address resolution protocol
**** responsible for resolving ip address to mac address
**** change the default gateway address so that computers connection to internet goes through attacher
*** denial of service
*** spoofing
**** pretending to be someone
* attack vectors
** vm and cloud environments
** unpatched software
** social networking
** hacktivism
** malware
** botnets
** secuirty staffing
** lack of security policies
** compliance with regulations/laws
** complexity of network infrastructure
** mobile devices
** ransomware
** advanced persistent threats
** phishing
** web applications
** iot
* ipv6
** auto configuration
** incompatibility of logging systems
** default activation
** shortcuts
** 4to6 translation
** multiple ips per device
** network discovery
* lab
** virtualbox
** hyper-v
** vmware
* recon
** find out number of ways we can attach the target
** methods to do recon
** trying to understand target and value
** 2 methods passive , active
* scanning
*** NIST - SP 800-115
*** PTES
*** OSSTMM
* tools
** maltego
* exam
** ec council certified ethical hacker exam
* jobs product secuirty incident response team
* information security vs cyber security
** In the past, security programs actually included policies and programs and technology like the traditional firewalls in place to actually block traffic from the outside or even from inside as well.
** those programs were originally designed only to protect the traditional CIA,
*** confidentiality, integrity, availability
*** confidentiality
**** protect sensitive data from being accessed and being read by unauthorized users.
**** use encryption for mitigation
*** integrity
**** data or systems have not been altered or modified by an attacker
**** hashing
*** availability
**** make sure that all systems are available at all the time to authorized users
**** ddos is major attack
** cyber security
*** includes lot other elements
*** organizations definitely have to be vigilant, resilient, and ready to protect, but also to defend in the case of an incident
*** dfir - digital forensics incident response
**** ability for you to build a program in place, not only technology, but also people to be able to respond to incident
**** Security operation center is basically the heart of an incident response program
***** Security Information and Event Management (SIEM)
***** security orchestration, automation, and response
****** analysts basically,act and work in a tier deployment
**** security orchestration, automation, and response, a term called SOAR.
*** risk management and oversight.
**** operationalize the way that you look at risk
**** prioritize things
**** create even heatmaps to see what devices and what environments may be of higher risk
**** potentially shift risk
**** able to discover the hidden risk
*** threat intelligence.
**** may be from a business peer that observed an indicator of a compromise or attack or attack behavior that can be shared with others
**** organization can pay to a company to receive a threat intelligence feed
**** information about a potential attack
*** third party security.
**** business partner
**** where we check software we buy from vendor
**** you actually have to take into consideration the risk that you may actually be introducing within your organization
*** organization have 2 or 3 level soc
* 1.3 ethical hacking methodologies
* cyber kill chain
** will allow you to gain information about the tactics, techniques, and procedures that attackers use in real life scenarios.
** framework that was part of the intelligence driven defense solution provided by a company called Lockheed Martin.
** goes over is the day in the life of an attack
** reconnaissance
** WEAPONIZATION
*** Coupling exploit with backdoor into deliverable payload
** delivery
** exploitation
** installation
** command and control
*** add some backdoor into the system
** ACTIONS ON OBJECTIVES
* MITRE ATT&CK Framework
** similar to cyber kill chain
** including a plethora of additional information
* Surveying Ethical Hacking Methodologies
** main difference of course, is that you are actually have permission to perform those attacks and something that we actually call scope,
dictates what you can or cannot do against a system.

different ethical hacking methodologies
penetration testing execution standard
OWASP testing guide
NIST 800-115: Technical Guide to Information Security Testing and Assessment
open source security testing methodology manual
pre engagement interactions
Scoping things like NDAs or non-disclosure agreements, different disclosures
* penetration testing
** penetration testing execution standard
** OWASP testing guide
** nist 800-115
**  open source security testing methodology manual, or the OSS TMM
* 2.1 Introducing Footprinting Concepts and Methodologies
** first step in the hacking methodology
** also called recon
** public info from things like  DNS, WHOIS
* 2.2 Performing Footprinting through Search Engines
** attackers  use these search engines to gather sensitive information that is exposed on the internet.
** exploit database or exploit DB
* 2.3 Performing Footprinting through Web Services and Websites
** An attacker can get a lot of information about a company or about an organization just navigating through their websites
** just navigating through their website
** get information about the organization and underlying systems by just looking at the digital certificates
** At the very minimum, you have the root CA, but you can also have subordinate CAs
** You may actually see that if the organization is using weak crypto algorithms for their implementation here.
** trying to see if they have a robot.TXT file
** website owners use these robots.TXT file to give instructions about their sites to web crawlers.
** you actually can get a lot of different information about different content that the website may actually have without even navigating through it
* 2.4 Performing Footprinting through Social Networking Sites
* 2.5 Exploring Shodan
** Shodan is an amazing platform tool to perform reconnaissance of what is actually exposed out on the internet
** scanning the internet 24/7 from many different locations around the world
** you will see that there are tons and tons of different devices that are exposed on the internet with misconfigurations, with tons of vulnerabilities that have not been patched and also with weak crypto implementations or default credentials.
* 2.6 Understanding Email Footprinting
** Maltego to find very interesting emails related to any type of company or domain
** the attacker can then use this email address to potentially find log-in pages or any type of systems related to hacker.org. Let's say that website may have a slash admin account or area.
* 2.7 Understanding Whois Footprinting
**  ICANN in short is the primary body that is in charge of
*** maintaining and the management of IP address space
***  allocation of the IP addresses to many organizations.
*** Also about protocol parameters and the Domain Name System or DNS management,
*** registration of domains, you know, across the world.
** who is utility
* 2.8 Understanding DNS Footprinting
** zone transfer attack
** zone transfer is, is a mechanism used by DNS servers to update another DNS server by transferring the  contents of their database
** DNS is structured as a hierarchy, so that whenever you request DNS information, your request is actually passed up this hierarchy until a DNS server is found that can resolve the domain name request
** authoritative name servers that will be able to resolve the hacker.org or secretcorp.org or pearson.com, cisco.com, et cetera
** Nslookup
** hacker.org has four different IP addresses, and is doing DNS round-robin
** host command
** DNS zone transfer attack
** The secondary name server starts the process by requesting an SOA record.
** And SOA stands for the start of authority record
** type of resource in the DNS system containing administrative information about that zone.
** SOS record is then sent to the secondary server
** SOA has a serial number that is higher than the secondary will have, then you will need an update.
** the attacker can get a lot of information about the organization using a zone transfer attack.
** we're actually using the dig command with the AXFR for the zone transfer, and we have two domains, @nsztm1.digininja, and then zone transfer me
#+begin_src bash
dig axfr @nsztml.digi.ninja zonetransfer.me
#+end_src
* 2.9 Understanding Network Footprinting
** DNS resolution using the host command to the domain hacker.org
** do a quick who is, to the first IP address in the results.
** network range that the first address that we selected belongs to
** attacker can now focus his efforts or her efforts on the range from the 185.199.111.0. So from .1 all the way to 254.
** You can use things as simple as a trace route to that IP address
** trace route becomes a little bit more relevant because now you are seeing things that may be in between. Probably firewalls that may be blocking the trace route, or the different structures like routers or layer three switches and so on
** on-premise performing a pen test, trace route becomes a little bit more relevant because now you are seeing things that may be in between. Probably firewalls that may be blocking the trace route, or the different structures like routers or layer three switches and so on, that may be in between your PC or your machine all the way to the target device.
* 2.10 Surveying Footprinting Tools
** popular tool that help you automate a lot of the open source intelligence on footprinting enumeration called Recon-NG
** it has different modules that you can install and use things like DNS, reconnaissance, host enumeration, domain enumerations and so on.
** Netcraft, which basically is a repository of DNS base information that is very useful for numerating sub domains of a company.
#+begin_src bash
marketplace install netcraft
#+end_src
** Brute_host, which is basically part of the domain host modules within the Recon-NG.
* 2.11 Understanding Footprinting Countermeasures
** start by creating some awareness among your employees about the dangers of social engineering
** limiting sensitive information that can be otherwise not thought of sensitive information.
** always encrypt things
** Using privacy services on WhoIs lookup database
** disable directory listings on web servers
** many organizations subscribe to the tools such as shodan
* 3: Scanning Networks
** The common path to discover these hosts is to scan those networks using easily-accessible tools to find hosts with services exposed.
* 3.2 Exploiting Scanning Tools
** metasploit is a framework for penetration testing
*** running the TCP port scanner against
** Nmap is a network mapper
** hping3
*** You can craft packets with hping
*** ping tool operating on ICMP
** https://owasp.org/www-community/Vulnerability_Scanning_Tools list of scanning tools
* 3.3 Understanding Host Discovery
** we need to detect hosts that are alive, as well as the services that are running on those hosts.
** There's three common methods used, ICMP scanning, ARP scanning, and passive listening using sniffing
** if you are on the same line segment that system does not have a firewall running that is blocking ICMP, then you should expect to see an echo reply
** ICMP scanning ping sweep.
*** if you wanted to determine what hosts are online on this entire network sub-net?
*** Nmap is commonly used for this task.
** in order for a system to talk on a network, it needs to know a destination IP address, of course. Right? And, it needs to know a destination Mac address.
** If you need to get outside of your sub-net, then you need to talk to a router.
** who has the Mac address for, in this case, this network's case, 10.1.0.1
** ARP is another way determine live systems
** A couple of more tools for scanning ICMP, Angry IP scanner and What's Up Gold.
** if you are able to put your wireless interface into promiscuous mode, you can just listen to those wireless frames as they're floating around
* 3.4 Network Scanning Overview
** Next step is to determine what services are up and running on those hosts
** Common tools for that Nmap and Hping
** several service scanning techniques that are common.
*** full open
*** idle
*** stealth
** two common routed layer four protocols tcp, udp
** TCP
*** ip protocol 6
*** connection oriented
** udp
*** ip protocol 17
*** connectionless
** tcp threeway handshake
*** they need to synchronize what are called Sequence Numbers
*** sequence number informs the remote system where it thinks it knows the data is
***  SYN SYN ACK ACK
** tcp flags
** tools
*** nmap
**** live  host, operating system detection, service discovery, and service version discovery
*** for packet crafting, we have Hping.
* 3.5 Network Scanning Methods
** various types of scanning that we can do in order to determine if services are available
**
** countermeasures
*** stateful firewalls will protect against the majority of these attacks
*** IDS, IPS, signatures can detect those bad segment flags
*** proactively scan your assets both from inside and outside
*** Filtering ICMP at least from internet
*** host intrusion prevention in order to monitor your hosts. So if it does get past the firewall, we want the host to be able to protect themselves.
* 3.6 Network Scanning Demo
** we've just connected our laptop to the network and we need to figure out what's out there
** first thing we need to do is see what IP address we received on our computer
** ip addr to find out ip address
** So let's see what's out there arp scan
#+begin_src bash
nmap -n -sn 192.168.1.0/28
#+end_src
** Now let's do a TCP port scan and I'm gonna do a connect scan.
#+begin_src bash
nmap -sT -p1-1000 -Tinsane 192.168.1.0/28
nmap -sT 192.168.1.4
nmap -sV -P0 192.168.1.4
#+end_src
* 3.7 Performing OS Discovery (Banner Grabbing/OS Fingerprinting)
** Our goal with banner-grabbing is to deduce information about two things.
** One is the service that's running and secondly, the operating system that that service is running on.
** we consult vulnerability databases. We find something matching OpenSSH version 3.
** different ways to grab the banner active and passive
** countermeasures
*** Apache, gives you options to protect against it.
* 3.8 Scanning Beyond IDS and Firewall
** these methods rely upon the fact that you have access to something inside the network already.
** using applications on the inside of firewalls and intrusion detection systems in order to get your traffic through those perimeter defenses
** SSH tunneling.
** reverse proxy traffic through an SSH tunnel as well.
** HTTP tunneling
**  if you have a demilitarized zone that is being protected by a firewall, it's going to permit HTTP type protocols through it, if there's a web server on the other side of it.
** proxy servers
** protecting yourself from identification
** benefits of proxy servers
*** Anonymization
*** alter data.
*** filter
**** because we can see traffic  we can block things, stop bad things from going through
*** source address overload
****  where we have 200 hosts behind one single IP that can be done with a proxy server.
*** firewalling
** attacker benefits
*** hide the original requester
*** Man in the middle
**** alter data as well intercept data
*** internal access
**** If a compromised host has access to the internal network, attack traffic can be proxied through it to compromise other hosts.
*** chaining
** software
*** Proxy fire
***  Proxy switcher
*** onion
**** Tor is to anonymize sources, and it does this by using relay routers
* 3.9 Creating Network Diagrams
** Network diagramming falls into the documentation category
** when you are investigating a network, and finding those systems that are alive, and the services that are listening, the services that are responding, the vulnerabilities that exist. Creating a network diagram can help you map out the state of the network so you know where your traffic is flowing throughout the network
** A network diagram can exist as either a physical diagram or a logical diagram.
** we have a layer 2 broadcast domains.
*** Those could be virtual lans on a switch
*** Today's networks often consolidate networks onto single devices, multiple virtual lans, or V-lans, multiple routed IP networks, even traffic can leave a device, and then come back into the device.
*** virtual routing forwarding instance into another VRF in the same system
** software
*** Solar Winds called Lan Surveyor
*** SNMP, ICMP, WMI and VMware for this discovery
*** OPManager. from a company called ManageEngine
*** SNMP not just provides configuration information, but also provides utilization information for physical interfaces.
* 4: Enumeration
** gathering of usernames, machine names, shares, et cetera from hosts that are up and available on the network.
* 4.1 Introducing Enumeration Techniques
** goal for enumeration is to extract information about the systems that we are trying to compromise
** If we're able to figure out usernames by querying an LDAP database, we know what usernames to try when we're doing our brute force dictionary attack to try to log in as those users
* 4.2 Performing NetBIOS Enumeration
** NetBIOS is a protocol that you will often see on corporate environments or even your home network
** So the Windows systems today, even today still run NetBIOS for backward compatibility
** Server Message Block, or Microsoft SMB, is slowly replacing NetBIOS.
** tools
*** nbtstat
** looking for hosts that are offering NetBIOS shares or server message block shares. We want to look for essentially Windows systems that might be sharing files on the network
* 4.3 Performing SNMP Enumeration
** SNMP or Simple Network Management Protocol
** primarily used on networking devices so for example, Cisco routers and switches
** SNMP is used for management and monitoring of devices on the network
** SNMP, it's a tree like structure. It's a database of information
* 4.4 Performing LDAP Enumeration
** Lightweight Directory Access Protocol
** LDAP is a Directory service.
** It's a store for usernames and you can authenticate against it.
* 4.5 Performing NTP and NFS Enumeration
** It uses things called stratums. Stratum zero is you're talking to a satellite in the sky, it's got a nuclear doohickey in it that is deriving valid time.
** you can see hosts that are talking to NTP servers through the use of listing the peers that they're talking to.
** network file shares, it's a Unix thing
* 4.6 Performing SMTP and DNS Enumeration
** SMTP is used to send email
** DNS is used for translating names to IP addresses
* 4.7 Conducting Additional Enumeration Techniques
** IPSEC, file transfer, Server Message Block and Voice over IP
* 4.8 Surveying Enumeration Countermeasures
* sniffing
* 5.1 Introducing Sniffing Concepts
**  capture and analysis of traffic as it flows across a network
** wiretap through hubs or taps
** Hubs will share traffic amongst everybody in a broadcast domain
** tap wherein you are physically inserting yourself in the path of the wire
** lawful intercept
* 5.2 Performing MAC Attacks
* 5.3 Conducting DHCP Attacks
** used to assign an IP address
* 5.4 Performing ARP Poisoning
** Address Resolution Protocol is used to map a layer two MAC address to an IP address
** tools
*** ettercap
* 5.5 Performing Spoofing Attacks
* foot printingp
** first step in hacking methodology
** we gather information in this step
* 6.1 Introducing Social Engineering Concepts
* 1.4 information security controls, laws
** get out of jail free card and that is a statement or a document that your customer, right? will actually give you as the pen tester to basically prove that they are permitting you and they're allowing you to perform this type of testing and that you are authorized to basically demonstrate what an attacker can actually do
** computer fraud and abuse act
** national conference of state and legislatures.
** General Data Protection Regulation GDPR
* type of scanning we can do
** tcp connect scan
*** tries to establish a session
*** uses full 3 way hand shake syn, syn/ack, ack/rst
*** if syn > rst means port closed
*** if there are any network firewalls we may not even get reset
*** we can do syn flood by not sending reset after syn/syn/ack
*** we send reset to tell destination that it can tear down session
** xmas scan
*** in this we set fin, psh, urg flags to 1 in the header
*** if port is open you won't get any response
** null scan
*** TCP segment with no flag set
*** if we get no response port is open
*** if we get RST back port is closed
** idle scan
*** we will use a zombie host
**** someone unknowingly participating in this scan
*** we derive IP ID from zombie
*** we send SYN packet spoofing zombie IP
*** process
**** send SYN/ACK to zombie host
**** we will get RST back
**** there will be IP in that RST
**** we send SYN to destination with spoofed IP
**** if destination port is closed we will get RST to zombie
**** when we run SYN/ACK again, we'll get IP ID incremented by 1
**** we require zombie host to be silent
**** for port open IP ID will incremented by 2
**** operating system increments IP ID by one, for every packet it sends. it may increment it by some random number too
** inverse TCP flag scan
*** FIN/URG/PSH/NULL uses combination of these flags to determine if port is open
*** if port is open no response
*** if port is closed reset
** ACK flag scan
** network firewalls with stateful feature can filter these scans?
*** because these are invalid flag combinations
* network scanning tools
** nmap
** counter measures
*** stateful firewalls will protect from most but TCP connect and Half-open
*** IDS, IPS, signatures can detect those bad segment flags
*** proactively scan your assets b
oth from inside and outside
**** don't want to have a service that should be available on the inside of your network, be available on the outside
*** Filtering ICMP
**** Filter ICMP at least to and from the internet
**** Employ HIPS with behavior monitoring to detect and block scanning sources
* scanning network demo
** to find your ip do
#+begin_src
ip addr
#+end_src
** we can do nmap to find other systems in the network
#+begin_src
nmap -n -sn ip/mask
# -n means dont connvert to names
# -sn means arp scan
#+end_src
** next we do tcp scan
*** this is active scan
#+begin_src
nmap -sT -p1-1000 -Tinsane ip/mask
#+end_src
*** find default gateway
#+begin_src bash
ip router
#+end_src
** /etc/services is distributed by most linux/unix systems
* banner grabbing
** goal is to figure out the service on the machine and which OS it is running on
** two types active, passive
** active
*** we connect and try to get information
** passive
*** we sniff network, capture packets
** counter measures
*** apache gives ability to hide this info in response
*** we can return fals response
*** IIS has lockdown wizard
* scanning beyond ids and firewall
** these need access to something inside network already
** ssh tunneling
*** provides methods to tunnel network traffic
*** you can actually reverse proxy traffic through an SSH tunnel as well.
#+begin_src
ssh -L 5900:10.1.1.20:5900 nick@10.1.1.10
#+end_src
